# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fibre',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='saturates',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='sugars',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER'), ('STARTER', 'STARTER'), ('DESSERT', 'DESSERT'), ('BRUNCH', 'BRUNCH'), ('SNACK', 'SNACK'), ('MAIN', 'MAIN COURSE'), ('SIDE', 'SIDE DISH'), ('DRINK', 'DRINK'), ('COCKTAIL', 'COCKTAIL'), ('CANAPE', 'CANAPE')], max_length=20, verbose_name='recipe Type'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='update',
            field=models.DateField(auto_now_add=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date Uploaded'),
        ),
    ]
