# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-03 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergy',
            field=models.CharField(choices=[('MIL', 'Milk'), ('EGG', 'Egg'), ('NUT', 'Nut'), ('SOY', 'Soya'), ('WHE', 'Wheat'), ('FIS', 'Fish')], max_length=10, verbose_name='allergy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'EASY'), ('NORM', 'NORMAL'), ('HARD', 'HARD'), ('EXPERT', 'EXPERT')], max_length=10, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fibre',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.CharField(choices=[('MAG', 'Magazine'), ('WEB', 'Website'), ('BOOK', 'Book'), ('SOC', 'Social Club'), ('PRO', 'Professional')], max_length=3, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('BRE', 'Breakfast'), ('LUN', 'Lunch'), ('DIN', 'Dinner'), ('STA', 'Starter'), ('DES', 'Dessert'), ('STA', 'Starter'), ('BRU', 'Brunch'), ('SNA', 'Snack'), ('MAI', 'Main Course'), ('SID', 'Side Dish'), ('DRI', 'Drink'), ('COC', 'Cocktail'), ('CAN', 'Canape')], max_length=10, verbose_name='recipe Type'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='salt',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='saturates',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=4),
        ),
    ]
