# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-29 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utensil',
            name='recipeType',
        ),
        migrations.DeleteModel(
            name='Utensil',
        ),
    ]
