# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190507_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.CharField(choices=[('MAGAZINE', 'MAGAZINE'), ('NEWSPAPER', 'NEWSPAPER'), ('WEBSITE', 'WEBSITE'), ('BOOK', 'BOOK'), ('SOCIAL CLUB', 'SOCIAL CLUB'), ('PROFESSIONAL', 'PROFESSIONAL')], max_length=20, verbose_name='publisher'),
        ),
    ]
