# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190503_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.CharField(choices=[('MAG', 'Magazine'), ('WEB', 'Website'), ('BOOK', 'Book'), ('SOC', 'Social Club'), ('PRO', 'Professional')], max_length=10, verbose_name='publisher'),
        ),
    ]
