# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190503_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergy',
            field=models.CharField(choices=[('MILK', 'Milk'), ('EGG', 'Egg'), ('NUT', 'Nut'), ('SOYA', 'Soya'), ('WHEAT', 'Wheat'), ('FISH', 'Fish')], max_length=20, verbose_name='allergy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.CharField(choices=[('MAG', 'Magazine'), ('WEB', 'Website'), ('BOOK', 'Book'), ('SOC', 'Social Club'), ('PRO', 'Professional')], max_length=20, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('STARTER', 'Starter'), ('DESSERT', 'Dessert'), ('STARTER', 'Starter'), ('BRUNCH', 'Brunch'), ('SNACK', 'Snack'), ('MAIN', 'Main Course'), ('SIDE', 'Side Dish'), ('DRINK', 'Drink'), ('COCKTAIL', 'Cocktail'), ('CANAPE', 'Canape')], max_length=20, verbose_name='recipe Type'),
        ),
    ]
