# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190507_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
