# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190504_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergy',
            field=models.CharField(choices=[('MILK', 'MILK'), ('EGG', 'EGG'), ('NUT', 'NUT'), ('SOYA', 'SOYA'), ('WHEAT', 'WHEAT'), ('FISH', 'FISH')], max_length=20, verbose_name='allergy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.CharField(choices=[('MAGAZINE', 'MAGAZINE'), ('WEBSITE', 'WEBSITE'), ('BOOK', 'BOOK'), ('SOCIAL CLUB', 'SOCIAL CLUB'), ('PROFESSIONAL', 'PROFESSIONAL')], max_length=20, verbose_name='publisher'),
        ),
    ]
