# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_scalable'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
