# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20190509_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
