# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-10 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='published_date',
            new_name='published_Date',
        ),
    ]
