# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20190509_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
