# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-10 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20190510_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
