# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-12 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20190510_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='method',
        ),
    ]
