# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_recipe_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(max_length=1500),
        ),
    ]
