# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20190512_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
