# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20190514_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='suits',
            field=models.CharField(max_length=10),
        ),
    ]
